# Generated by Django 5.1 on 2024-08-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_data_id', models.IntegerField()),
                ('teacher', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('credit_num', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('current_people', models.IntegerField()),
                ('waiting_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('is_expired', models.BooleanField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.class')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('star', models.IntegerField()),
                ('keyword', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.class')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.reservation')),
            ],
        ),
    ]
