# Generated by Django 5.1.1 on 2024-09-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_reservation_center_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
