# Generated by Django 5.1 on 2024-09-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_alter_reservation_user_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='center_data_id',
            field=models.CharField(default='Default Center', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.CharField(default='Unknown Date', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='teacher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(default='Unknown Time', max_length=50),
        ),
    ]
