# Generated by Django 5.1 on 2024-09-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_alter_reservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='user_id',
        ),
    ]
