# Generated by Django 5.1 on 2024-09-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_rename_user_reservation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='current_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='waiting_people',
            field=models.CharField(default='', max_length=100),
        ),
    ]
