# Generated by Django 5.1 on 2024-09-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0012_rename_user_id_reservation_user_alter_class_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='class_instance',
            new_name='class_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
