# Generated by Django 5.1 on 2024-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0014_alter_reservation_user_id_alter_review_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='center_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
