# Generated by Django 5.1 on 2024-09-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signInUp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
