# Generated by Django 5.1 on 2024-09-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signInUp', '0004_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.BooleanField(default=False)),
                ('using_credit', models.IntegerField(default=0)),
                ('remaining_credit', models.IntegerField(default=0)),
                ('credit_period', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signInUp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
