# Generated by Django 5.1 on 2024-09-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signInUp', '0006_alter_userprofile_using_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='remaining_credit',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='using_credit',
            field=models.IntegerField(default=0),
        ),
    ]
