# Generated by Django 5.1.1 on 2024-09-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signInUp', '0008_alter_userprofile_using_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
