# Generated by Django 5.1 on 2024-09-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credit_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
