# Generated by Django 5.1 on 2024-09-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0009_class_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='credit',
        ),
    ]
