# Generated by Django 5.1 on 2024-09-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0010_remove_reservation_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='center_name',
            field=models.CharField(default='Default Center', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.CharField(default='Unknown Date', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='teacher_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(default='Unknown Time', max_length=50),
        ),
    ]
