# Generated by Django 5.1 on 2024-09-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0011_reservation_center_name_reservation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='center_name',
            new_name='center_data_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='teacher_name',
            new_name='teacher',
        ),
    ]
