# Generated by Django 5.1 on 2024-09-08 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0014_alter_reservation_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='center_data_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='current_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='waiting_people',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='center_data_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='credit_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='detail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_expired',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('keyword', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPage.class')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPage.reservation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
