# Generated by Django 5.1 on 2024-09-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0020_rename_user_reservation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='center_data_id',
            new_name='center_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='class_id',
            new_name='class_instance',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='class',
            name='waiting_people',
            field=models.CharField(default='', max_length=100),
        ),
    ]
