# Generated by Django 5.1.1 on 2024-09-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0025_reservation_center_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
