# Generated by Django 5.1.1 on 2024-09-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0026_userprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
